import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import Navigation from "@/components/Navigation";
import QueryProvider from "@/components/QueryProvider";


const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassName = `${roboto.variable} antialiased`;
  
  return (
    <html lang="en" className={bodyClassName}>
      <body suppressHydrationWarning={true}>
        <QueryProvider>
          <ThemeProvider>
            <Navigation />
            {children}
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
